---
- name: Setup compose dir structure
  file:
    path: "{{ compose_project_dir }}/{{ item }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    recurse: yes
    mode: 0755
  with_items:
  - wordpress
  - wp-db-data
  - logs/nginx

- name: Create docker-compose.yml file
  file:
    path: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: touch

- name: Deploy uploads.ini to WordPress "{{ compose_project_dir }}" dir
  copy:
    src: "{{ role_path }}/files/uploads.ini"
    dest: "{{ compose_project_dir }}/wordpress/"
    owner: "www-data"
    group: "www-data"
    mode: 0644

- name: Deploy Docker Compose project for Wordpress/MySQL/Nginx (Let's Encrypt) containers
  template:
    src: docker-compose.j2
    dest: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644

- name: Run docker-compose up
  command: docker-compose -f docker-compose.yml up -d
  args:
    chdir: "{{ compose_project_dir }}"

- name: Waiting for all containers to start up and {{ domain }} to be accessible
  wait_for:
    host: "{{ domain }}"
    port: 80
    timeout: 180
  register: host_accessible
  failed_when: False

- debug:
    msg: "Site is reachable"
  when: host_accessible.state is defined and host_accessible.state == "started"

- debug:
    msg: "Site is NOT reachable"
  when: host_accessible.state is defined and host_accessible.state == "stopped"

# debug output
- debug:
    msg:
      - "With specified variables, following configuration has been made:"
      - ""
      - "URL used for Nginx virtual host: {{ domain }}"
      - "Specified URL is live/DNS is setup: {{ stage }}"
      - "WordPress Docker image version:{{ wp_version }}"
      - "WORDPRESS_DB_NAME: {{ wp_db_name }}"
      - "WORDPRESS_TABLE_PREFIX: {{ wp_db_tb_pre }}"
      - "WORDPRESS_DB_HOST: {{ wp_db_host }}"
      - "WORDPRESS_DB_USER: {{ wp_db_user }}"
      - "WORDPRESS_DB_PASSWORD: {{ wp_db_psw }}"
      - "MYSQL_ROOT_PASSWORD: {{ db_root_psw }}"
      - "MYSQL_DATABASE: {{ wp_db_name }}"
      - "MYSQL_USER: {{ wp_db_user }}"
      - "MYSQL_PASSWORD: {{ wp_db_psw }}"

- debug:
    msg:
      - "Setup successfully complete."
      - ""
      - "Wordpress instance is available on following IP: {{ inventory_hostname }}"
      - "If DNS is pointing to this IP, it'll be available on: {{ domain }}"
